# Generated by Django 5.1.1 on 2024-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdescription",
            name="created_at",
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="job_file",
            field=models.FileField(
                default="path/to/default/file.txt", upload_to="Jobs/"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(upload_to="CV/"),
        ),
    ]
